name: OWASP ZAP Integration with GitHub Actions

on: [push]

permissions:
  contents: read
  issues: write

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-a'

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-reports
          path: |
            report_json.json
            report_md.md
            report_html.html
