name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Zap Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://testphp.vulnweb.com/'
          cmd_options: '-a'